# fly.toml app configuration file generated for all-telegram-bots on 2026-04-18T12:06:01-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'all-telegram-bots'
primary_region = 'dfw'

[build]

[processes]
  app = "python main.py"

[[vm]]
  memory = '512mb'
  cpus = 1
  memory_mb = 512
