app = "all-telegram-bots"
primary_region = "iad"

[build]

[env]
  PYTHONUNBUFFERED = "1"

[deploy]
  strategy = "immediate"

[processes]
  app = "python austin311_bot.py"

[[mounts]]
  source      = "austin311_data"
  destination = "/data"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256
